---
title: "Probability Theory"
---

---
Assignement 1:
---

```{r}
prob_of_s <- 0.3
prob_of_sbar <- 0.7
prob_of_t_knowing_s <- 0.2
prob_of_tbar_knowing_s<- 0.8
prob_of_t_knowing_sbar<- 0.6
prob_of_tbar_knowing_sbar <- 0.4

prob_of_s_and_t <- prob_of_t_knowing_s*prob_of_s
print("prob_of_s_and_t:")
print(prob_of_s_and_t)
prob_of_s_and_tbar <- prob_of_tbar_knowing_s*prob_of_s
print("prob_of_s_and_tbar:")
print(prob_of_s_and_tbar)
prob_of_sbar_and_t <- prob_of_t_knowing_sbar*prob_of_sbar
print("prob_of_sbar_and_t:")
print(prob_of_sbar_and_t)
prob_of_sbar_and_tbar <- prob_of_tbar_knowing_sbar*prob_of_sbar
print("prob_of_sbar_and_tbar:")
print(prob_of_sbar_and_tbar)

```

--- 
Assignement 2:
---
The percentage of customers using all three devices = 0.5%

The percentage of customers using at least two devices = 8.8% + 7.3% +3.3% = 19.4%

The percentage of customers using only one device = 42.3% + 10% + 27.8% = 80.1% 

---
Assignement 3:
---

```{r}
prob_of_a<- 0.04
prob_of_b_knowing_a <- 0.97
prob_of_b_knowing_abar<- 0.01

prob_of_abar= 1-prob_of_a
prob_of_abar_knowing_b <- (prob_of_b_knowing_abar*prob_of_abar)/((prob_of_b_knowing_abar*prob_of_abar)+(prob_of_b_knowing_a*prob_of_a))
print("prob_of_abar_knowing_b:")
print(prob_of_abar_knowing_b)
prob_of_a_knowing_b <- (prob_of_b_knowing_a*prob_of_a)/((prob_of_b_knowing_abar*prob_of_abar)+(prob_of_b_knowing_a*prob_of_a))
print("prob_of_a_knowing_b:")
print(prob_of_a_knowing_b)
```

