---
title: "Difference-in-Differences"
---

```{r}
library(tidyverse)
hospdd <- readRDS("hospdd.rds")
treated <- hospdd%>% filter(procedure==1&month>3)%>%pull(hospital)
control <- hospdd%>% filter(procedure==0&month>3)%>%pull(hospital)
View(treated)
View(control)
satis_treated_before_treatment <- hospdd%>% filter(hospdd$hospital %in% treated==TRUE,month<4)%>% pull(satis)
mean(satis_treated_before_treatment)

satis_treated_after_treatment <- hospdd%>% filter(hospdd$hospital %in% treated==TRUE,month>3)%>% pull(satis)
mean(satis_treated_after_treatment)

satis_control_before_treatment <- hospdd%>% filter(hospdd$hospital %in% control==TRUE,month<4)%>% pull(satis)
mean(satis_control_before_treatment)

satis_control_after_treatment <- hospdd%>% filter(hospdd$hospital %in% control==TRUE,month>3)%>% pull(satis)
mean(satis_control_after_treatment)
```
```{r}
# Step 1: Difference between treatment and control group BEFORE treatment
 satis_treated_before_treatment <- hospdd%>% filter(hospdd$hospital %in% treated==TRUE,month<4)%>% pull(satis)

satis_treated_after_treatment <- hospdd%>% filter(hospdd$hospital %in% treated==TRUE,month>3)%>% pull(satis)

satis_control_before_treatment <- hospdd%>% filter(hospdd$hospital %in% control==TRUE,month<4)%>% pull(satis)

satis_control_after_treatment <- hospdd%>% filter(hospdd$hospital %in% control==TRUE,month>3)%>% pull(satis)

# Difference between treatment and control group BEFORE treatment
diff_before_treat <- c(satis_treated_before_treatment,replicate(620,0)) - satis_control_before_treatment

# Difference between treatment and control group AFTER treatment
diff_after_treat <- c(satis_treated_after_treatment,replicate(620,0)) - satis_control_after_treatment


after <- as.numeric(ifelse(hospdd$month > 4, 1, 0))

summary(lm(satis ~ (month*after+month+hospital) , data = hospdd))

summary(lm(satis ~ month*after+as.factor(hospdd$month) + as.factor(hospdd$hospital) , data = hospdd ))

"The  difference between the two methods is that when you consider the variables month and hospital as a factor, it forms a vector of values from these variables."
```

